version: '3'
services:
  db:
    image: mariadb:latest
    container_name: go-bookstore-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: go_database
      MARIADB_USER: go_test
      MARIADB_PASSWORD: password
      TZ: 'Europe/Helsinki'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - go-crud
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_USER=go_test
      - PMA_PORT=3306
      - PMA_PASSWORD=password
    ports:
      - 9090:80
    restart: always
    networks:
      - go-crud

volumes:
  db-data:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  go-crud:
    driver: bridge